<?php
/**
 * Created by PaiPaiYou.
 * User: wubang
 * Date: 2018-10-09 14:02
 * Email: domewubang@gmail.com
 */
namespace app\components\identity;

use yii\base\Component;

class User extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}