<?php
namespace app\apps\user\controllers;

use app\apps\Controller;
use app\apps\user\validates\BaseValidate;

class BaseController extends Controller
{
    /**
     * @var BaseValidate
     */
    public $validator;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}